steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME}', '-f', 'Dockerfile', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']

# Store images in Google Container Registry
images:
  - '${_IMAGE_NAME}'

# Build configuration
timeout: '1800s'
options:
  logging: CLOUD_LOGGING_ONLY 